version: '3.7'

services:
  fuel-counter:
    container_name: fuel-counter
    build: ../fuel-counter
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start